# Generated by Django 4.2.13 on 2024-07-04 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.PositiveIntegerField()),
                ('age_max', models.PositiveIntegerField()),
                ('caste', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('height_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('income_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qualification', models.CharField(choices=[('SSLC', 'SSLC'), ('PLUSTWO', 'Plus Two'), ('BACHELOR', 'Bachelors'), ('MASTERS', 'Masters'), ('PHD', 'PhD')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('siblings_count', models.PositiveIntegerField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('caste', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('zodiac_sign', models.CharField(max_length=100)),
                ('horoscope', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parents_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
