# Generated by Django 4.2.13 on 2024-07-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsdetails',
            name='country',
            field=models.CharField(choices=[('INDIA', 'India')], default='NONE', max_length=10, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='parentsdetails',
            name='district',
            field=models.CharField(choices=[('ALAPPUZHA', 'Alappuzha'), ('ERNAKULAM', 'Ernakulam'), ('IDUKKI', 'Idukki'), ('KASARAGOD', 'Kasaragod'), ('KOZHIKODE', 'Kozhikode'), ('KOLLAM', 'Kollam'), ('KOTTAYAM', 'Kottayam'), ('MALAPPURAM', 'Malappuram'), ('PALAKKAD', 'Palakkad'), ('PATHANAMTHITTA', 'Pathanamthitta'), ('THIRUVANANTHAPURAM', 'Thiruvananthapuram'), ('THRISSUR', 'Thrissur'), ('WAYANAD', 'Wayanad')], default='NONE', max_length=25, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='parentsdetails',
            name='state',
            field=models.CharField(choices=[('KERALA', 'Kerala'), ('TAMILNADU', 'Tamilnadu')], default='NONE', max_length=10, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='parentsdetails',
            name='annual_income',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parentsdetails',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parentsdetails',
            name='horoscope',
            field=models.FileField(upload_to='horoscopes/'),
        ),
        migrations.AlterField(
            model_name='parentsdetails',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='height_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='height_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='income_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='income_min',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='weight_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='weight_min',
            field=models.PositiveIntegerField(),
        ),
    ]
