# Generated by Django 4.2.13 on 2024-07-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyApp', '0002_parentsdetails_country_parentsdetails_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsdetails',
            name='zodiac_sign',
            field=models.CharField(choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=100),
        ),
    ]
