# Generated by Django 4.2.13 on 2024-07-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyApp', '0003_alter_parentsdetails_zodiac_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsdetails',
            name='caste',
            field=models.CharField(choices=[('Brahmin', 'Brahmin'), ('Kshatriya', 'Kshatriya'), ('Vaishya', 'Vaishya'), ('Shudra', 'Shudra'), ('Dalit', 'Dalit'), ('Koli', 'Koli'), ('Gujar', 'Gujar'), ('Lodhi', 'Lodhi'), (' Yadav', 'Yadav'), ('Jat', 'Jat'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='parentsdetails',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Sikhism', 'Sikhism'), ('Judaism', 'Judaism'), ('Baha’i', 'Baha’i'), ('Jainism', 'Jainism'), ('Shintoism', 'Shintoism'), ('Cao Dai', 'Cao Dai'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='caste',
            field=models.CharField(choices=[('Brahmin', 'Brahmin'), ('Kshatriya', 'Kshatriya'), ('Vaishya', 'Vaishya'), ('Shudra', 'Shudra'), ('Dalit', 'Dalit'), ('Koli', 'Koli'), ('Gujar', 'Gujar'), ('Lodhi', 'Lodhi'), (' Yadav', 'Yadav'), ('Jat', 'Jat'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='partnerpreference',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Sikhism', 'Sikhism'), ('Judaism', 'Judaism'), ('Baha’i', 'Baha’i'), ('Jainism', 'Jainism'), ('Shintoism', 'Shintoism'), ('Cao Dai', 'Cao Dai'), ('Others', 'Others')], max_length=100),
        ),
    ]
