# Generated by Django 4.2.13 on 2024-07-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyApp', '0008_profileinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinteraction',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('requested', 'Requested'), ('not_interested', 'Not Interested'), ('accepted', 'Accepted')], max_length=20),
        ),
    ]
