# Generated by Django 4.2.13 on 2024-07-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyApp', '0010_friendrequest_delete_profileinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
