# Generated by Django 4.2.13 on 2024-07-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyApp', '0011_friendrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
