# Generated by Django 4.2.13 on 2024-07-16 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimonyApp', '0012_alter_friendrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excluded_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'excluded_profile')},
            },
        ),
    ]
