# Generated by Django 4.2.13 on 2024-07-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyApp', '0014_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsdetails',
            name='interested_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], default='both', max_length=6),
        ),
    ]
