# Generated by Django 4.2.13 on 2024-07-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyApp', '0015_parentsdetails_interested_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsdetails',
            name='interested_gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('BOTH', 'Both')], default='BOTH', max_length=6),
        ),
    ]
