# Generated by Django 4.2.13 on 2024-07-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonyApp', '0019_paymentdetail_invoice_id_paymentdetail_session_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='hosted_invoice_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='receipt_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
