# Generated by Django 4.2.13 on 2024-07-31 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrimonyApp', '0022_alter_paymentdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
