# Generated by Django 4.2.13 on 2024-07-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, choices=[('SSLC', 'SSLC'), ('PLUSTWO', 'PLUSTWO'), ('BACHELOR', 'BACHELOR'), ('MASTERS', 'MASTERS'), ('PHD', 'PHD')], max_length=50, verbose_name='Education level'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender'),
        ),
    ]
