# Generated by Django 4.2.13 on 2024-07-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_age_user_education_level_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drinking_status',
            field=models.CharField(choices=[('Non-drinker', 'Non-drinker'), ('Drinker', 'Drinker'), ('Occasional', 'Occasional')], default='Non-drinker', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='smoking_status',
            field=models.CharField(choices=[('Non-smoker', 'Non-smoker'), ('Smoker', 'Smoker'), ('Occasional', 'Occasional')], default='Non-smoker', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Phone number'),
        ),
    ]
