# Generated by Django 4.2.13 on 2024-07-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_company_name_user_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
    ]
