# Generated by Django 4.2.13 on 2024-07-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationship_type',
            field=models.CharField(choices=[('short_term', 'Short Term'), ('long_term', 'Long Term')], default='short_term', max_length=10),
        ),
    ]
