# Generated by Django 4.2.13 on 2024-07-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_relationship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship_type',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('short_term', 'Short Term'), ('long_term', 'Long Term')], max_length=10),
        ),
    ]
